### PR TITLE
Array Prototypes - Memoize Project - Path 1

### PR DESCRIPTION
**Pull request by pvinthemix**
Building an array prototype flashcard application. The user will be able to see the name of an array prototype and then be presented with its use-case, what type of array prototype it is, and the number of parameters it takes. The user will also be able to cycle through the prototypes at random or go through each one by one.

This app should allow students a excellent resources for getting more familiar with the array prototypes used in the wild. Students should be able to intialize those prototypes they need to work on more at a different time.

screen shot 2018-11-02 at 10 29 43 am

### CODE REVIEW

**Comment by thatPamIAm** [comment]
@pvinthemix Make sure that you run your data through a JSON validator for syntax

**Comment by pvinthemix** [comment]
@thatPamIAm It should be all set. I think the exports maybe was off?

**Comment by pvinthemix** [comment]
screen shot 2018-11-02 at 10 17 01 am

**Comment by thatPamIAm** [comment]
@pvinthemix Yup - looks good. Data set looks good so far - curious as to what your plan is for the the flashcards? What will the interaction be? How will you be keeping track of right/wrong answers?

**Comment by pvinthemix** [comment]
Wireframe as well

**Comment by brittanystoroz** [comment]
@pvinthemix Just to confirm, the little 'Bookmark' link in your wireframe will allow users to essentially 'favorite' or 'star' a particular prototype method they need more practice with? (I'd imagine this would be your use-case for implementing localStorage as well?)

**Comment by pvinthemix** [comment]
@brittanystoroz Yep that is correct. The localStorage portion will allow the user to revisit to the ones they have the bookmark/starred in a different session.

**Pull request merged**
